# Generated by Django 5.0.3 on 2024-06-22 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sagasouls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('company', models.CharField(max_length=128)),
                ('GOTY', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('subgenero', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('directors', models.ManyToManyField(blank=True, to='sagasouls.director')),
                ('genero', models.ManyToManyField(blank=True, to='sagasouls.genero')),
                ('sagasouls', models.ManyToManyField(blank=True, to='sagasouls.sagasouls')),
            ],
        ),
    ]
